name: Post Merge

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

permissions:
  contents: read

concurrency: lambda-post-merge

jobs:
  tests:
    uses: ./.github/workflows/_run-tests.yml

  tag-release:
    needs:
      - tests
    permissions:
      contents: write
    uses: ./.github/workflows/_create_release_tag_for_version.yml
